project_name: terraform-provider-hetzner

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: "{{.ProjectName}}_v{{.Version}}"

archives:
  - format: zip
    name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}_{{.Arch}}"

checksum:
  name_template: "{{.ProjectName}}_{{.Version}}_SHA256SUMS"

signs:
  - cmd: gpg
    artifacts: checksum
    args:
      - "--batch"
      - "--yes"
      - "--armor"
      - "--detach-sign"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase-fd"
      - "0"                # passphrase comes from stdin
      - "--output"
      - "${signature}"
      - "${artifact}"
    stdin: "{{ .Env.GPG_PASSPHRASE }}"

release:
  prerelease: auto
