project_name: terraform-provider-hetzner

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: terraform-provider-hetzner

archives:
  - format: zip
    name_template: "terraform-provider-hetzner_v{{.Version}}_{{.Os}}_{{.Arch}}"

checksum:
  name_template: "SHA256SUMS"

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--yes"
      - "--armor"
      - "--detach-sign"
      - "--local-user={{ .Env.GPG_FINGERPRINT }}"

release:
  prerelease: auto
